# Copyright (c) 2022, Oracle and/or its affiliates.
# Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.

grafana:
  enabled: false
nodeExporter:
  enabled: false
kubeStateMetrics:
  enabled: false
prometheus:
  enabled: true
  prometheusSpec:
    additionalScrapeConfigsSecret:
      enabled: true
      name: additional-scrape-configs
      key: jobs
    containers:
    - name: tls-secret-generator
      volumeMounts:
        - mountPath: /etc/istio-certs
          name: istio-certs-dir
  additionalRulesForClusterRole:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
      - list
      - watch
      - update
      - create
  - apiGroups:
      - monitoring.coreos.com
    resources:
      - prometheuses
    verbs:
      - get
      - list
      - watch
alertmanager:
  enabled: false
prometheusOperator:
  admissionWebhooks:
    enabled: true
    patch:
      enabled: true
  tls:
    enabled: true
