# Copyright (c) 2022, Oracle and/or its affiliates.
# Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.


elasticsearch:
  enabled: true
kibana:
  enabled: true
kubeStateMetrics:
  enabled: true
prometheusAdapter:
  enabled: true
prometheusNodeExporter:
  enabled: true
prometheusOperator:
  enabled: true
prometheusPushgateway:
  enabled: true

