# Copyright (c) 2022, Oracle and/or its affiliates.
# Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.

ingress:
  name: test
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    dns.verrazzano.io/set-host: "true"
  hosts:
  - host: hello
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: hello
            port:
              number: 80

