# Copyright (c) 2022, Oracle and/or its affiliates.
# Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.

name: default
enabled: false
annotations: {}
  # kubernetes.io/ingress.class: nginx
  # kubernetes.io/tls-acme: "true"
hosts:
  - host: chart-example.local
    http:
      paths: []
tls: []
#  - secretName: chart-example-tls
#    hosts:
#      - chart-example.local

